services:
  gui:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
        USER: ${USER}
    container_name: gui
    hostname: gui
    volumes:
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
        rw: true
    environment:
      DISPLAY: ${DISPLAY}
    entrypoint: tail -f /dev/null
