services:
  gui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gui
    network_mode: "host"
    volumes:
      - type: bind
        source: ${HOME}/.Xauthority
        target: /root/.Xauthority
        ro: true
    environment:
      DISPLAY: ${DISPLAY}
    entrypoint: /usr/bin/xeyes
